List<Map<String, dynamic>> dados = [
  {
    "Data": "06/jul",
    "Empresa": "Germany Garage",
    "Valor": 90.00,
    "Parcelas": "02/dez",
    "Categoria": "Manutenção",
    "Produto": "Câmera de Ré",
  },
  {
    "Data": "06/jul",
    "Empresa": "Park Zone",
    "Valor": 24.00,
    "Parcelas": "0",
    "Categoria": "Estacionamento",
    "Produto": "Estacionamento Shop, Ibira",
  },
  {
    "Data": "06/jul",
    "Empresa": "Germany Garage",
    "Valor": 250.00,
    "Parcelas": "11/dez",
    "Categoria": "Manutenção",
    "Produto": "Multimídia",
  },
  {
    "Data": "06/jul",
    "Empresa": "Shell",
    "Valor": 161.74,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Posto Bola Pesada",
  },
  {
    "Data": "10/jul",
    "Empresa": "Sumup",
    "Valor": 1985.53,
    "Parcelas": "0",
    "Categoria": "Lazer",
    "Produto": "Winter Wonderland Bulgária",
  },
  {
    "Data": "13/jul",
    "Empresa": "Amazon",
    "Valor": 52.00,
    "Parcelas": "0",
    "Categoria": "ComprasInternet",
    "Produto": "Vonixx Shiny",
  },
  {
    "Data": "14/jul",
    "Empresa": "Vans",
    "Valor": 96.67,
    "Parcelas": "01/mar",
    "Categoria": "Lazer",
    "Produto": "Chapéu Anaheim Sidewall Natural",
  },
  {
    "Data": "16/jul",
    "Empresa": "Kodeco",
    "Valor": 2390.77,
    "Parcelas": "0",
    "Categoria": "Estudos",
    "Produto": "Curso Swift",
  },
  {
    "Data": "18/jul",
    "Empresa": "Drogaria São Paulo",
    "Valor": 33.74,
    "Parcelas": "01/fev",
    "Categoria": "Saúde",
    "Produto": "Bye Bad",
  },
  {
    "Data": "18/jul",
    "Empresa": "San Paolo Gelateria",
    "Valor": 23.50,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Gelato",
  },
  {
    "Data": "22/jul",
    "Empresa": "Pizza King",
    "Valor": 36.00,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Rodízio",
  },
  {
    "Data": "22/jul",
    "Empresa": "Boteco e Petiscaria Th",
    "Valor": 6.00,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "H2O",
  },
  {
    "Data": "23/jul",
    "Empresa": "Milklandia Chocolates",
    "Valor": 45.90,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Chocolates",
  },
  {
    "Data": "23/jul",
    "Empresa": "Boteco e Petiscaria Th",
    "Valor": 16.00,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Strawberry Lemonade",
  },
  {
    "Data": "27/jul",
    "Empresa": "Hangar das Artes",
    "Valor": 15.00,
    "Parcelas": "0",
    "Categoria": "Casa",
    "Produto": "Imã decorativo",
  },
  {
    "Data": "27/jul",
    "Empresa": "Livraria Cultura",
    "Valor": 69.90,
    "Parcelas": "0",
    "Categoria": "Estudo",
    "Produto": "Livro",
  },
  {
    "Data": "27/jul",
    "Empresa": "Duty-Free SSA Airport",
    "Valor": 29.90,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Chocolates",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "FastFood",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 169.18,
    "Parcelas": "0",
    "Categoria": "Outros",
    "Produto": "Sushi",
  },
  {
    "Data": "28/jul",
    "Empresa": "Gasper Pneus e Rodas",
    "Valor": 187.50,
    "Parcelas": "01/abr",
    "Categoria": "Manutenção",
    "Produto": "Instação Câmera de Ré + Coding",
  },
  {
    "Data": "29/jul",
    "Empresa": "Petrobras",
    "Valor": 81.42,
    "Parcelas": "0",
    "Categoria": "Gasolina",
    "Produto": "Auto Posto Zezao",
  },
  {
    "Data": "29/jul",
    "Empresa": "Iwata Sushi",
    "Valor": 1200.0,
    "Parcelas": "0",
    "Categoria": "Outros",
    "Produto": "Sushi",
  },
];
